Fix build
ome/ansible-role-nginx pull request #13
Opened 2023-06-16 15:13 UTC by pwalczysko

Similar to https://github.com/ome/ansible-role-basedeps/pull/11

cc @sbesson @jburel

2023-06-16 21:37 UTC, sbesson approved these changes

2023-06-19 07:26 UTC, pwalczysko commented
Although the changes are similar to the other repos like https://github.com/ome/ansible-role-ice/pull/21, there is some (yet inexplicable for me) failure of the test assertion. I will investigate after AL.

2023-06-29 18:52 UTC, pwalczysko commented
@sbesson this is green now, also removed the ubuntu1804 as in the other repos. Please merge if happy.

2023-06-30 07:51 UTC, sbesson requested changes
One suggestion to match the Ubuntu 18.04 support removal. Otherwise good to merge

2023-06-30 07:51 UTC, sbesson commented on meta/main.yml
>          - bionic
Maybe let's remove this line from the metadata file to indicate support for Ubuntu 18.04 is dropped

2023-06-30 09:16 UTC, sbesson commented on meta/main.yml
>          - bionic
Sorry, I actually meant the whole `Ubuntu` block

2023-06-30 09:23 UTC, pwalczysko commented
> Sorry, I actually meant the whole `Ubuntu` block

This is now fixed, thanks.

2023-07-18 09:04 UTC, pwalczysko commented
Do we want to merge @jburel please ?

2023-07-18 09:18 UTC, merged